apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linstor-satellite
  namespace: linstor
spec:
  selector:
    matchLabels:
      app: linstor-satellite
  template:
    metadata:
      labels:
        app: linstor-satellite
    spec:
      nodeSelector:
        linstor-satellite: ""
      hostNetwork: true
      hostPID: true
      hostIPC: true

      initContainers:
      - name: init
        image: kvaps/linstor-satellite:latest
        securityContext:
          privileged: true
        command:
        - "/bin/sh"
        - "-c"
        - |
            cat /config/drbd.conf > /etc/drbd.conf
            cp -f /config/global_common.conf /etc/drbd.d/global_common.conf
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: etc-drbd-conf
          mountPath: "/etc/drbd.conf"
        - name: etc-drbd-d
          mountPath: "/etc/drbd.d"
        - name: usr-local-sbin
          mountPath: "/host-bin"

      containers:
      - name: linstor-satellite
        image: kvaps/linstor-satellite:latest
        securityContext:
          privileged: true
        terminationMessagePath: /termination-log
        volumeMounts:
        - name: etc-drbd-conf
          mountPath: "/etc/drbd.conf"
        - name: etc-drbd-d
          mountPath: "/etc/drbd.d"
        - name: var-lib-drbd
          mountPath: "/var/lib/drbd"
        - name: var-lib-linstor-d
          mountPath: "/var/lib/linstor.d"
        - name: lib-modules
          mountPath: "/lib/modules"
        - name: dev
          mountPath: "/dev"

      volumes:
        - name: etc-drbd-conf
          hostPath:
            path: "/etc/drbd.conf"
            type: FileOrCreate
        - name: etc-drbd-d
          hostPath:
            path: "/etc/drbd.d"
        - name: var-lib-drbd
          hostPath:
            path: "/var/lib/drbd"
        - name: var-lib-linstor-d
          hostPath:
            path: "/var/lib/linstor.d"
        - name: lib-modules
          hostPath:
            path: "/lib/modules"
        - name: usr-local-sbin
          hostPath:
            path: "/usr/local/sbin"
        - name: dev
          hostPath:
            path: "/dev"
        - name: config
          configMap:
            name: drbd-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drbd-config
  namespace: linstor
data:
  drbd.conf: |
    include "drbd.d/global_common.conf";
    include "drbd.d/*.res";
  global_common.conf: |
    global {
     usage-count no;
     udev-always-use-vnr;
    }
    common {
     handlers {
     }
     startup {
     }
     options {
     }
     disk {
     }
     net {
     }
    }
